//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_project_v0._0._2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ticketID { get; set; }
        public int sessionID { get; set; }
        public int userID { get; set; }
        public string filmName { get; set; }
        public int price { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public int row { get; set; }
        public int place { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual UsersBD UsersBD { get; set; }
    }
}
